version: "3.3"
services:
  app:
    image: app
    build: .
    ports:
    - target: 5000
      published: 80
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - target: 8080
        published: 8080
